config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recipes, only: [:index, :show]

  root 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ContentfulModel::Base
  self.content_type_id = "recipe"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all.load
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MsChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, user-scalable=no">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light border-bottom mb-5">
      <a class="navbar-brand" href="/">Marley Spoon Challenge</a>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="container">
  <div class="row">
    <% @recipes.each do |recipe| %>
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <%= link_to recipe_path(recipe.id) do %>
          <div class="recipe-card card mb-4">
            <%= image_tag recipe.photo.url(width: 250, height: 250), class: 'card-img-top' %>
            <div class="card-body">
              <p class="card-text"><%= recipe.title %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="row mb-4">
    <div class="col recipe-detail-img-container">
      <%= image_tag @recipe.photo.url %>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <h1><%= @recipe.title %></h1>
      <div>
        <% @recipe.tags&.each do |tag| %>
          <span class="badge badge-info"><%= tag.name %></span>
        <% end %>
      </div>
      <p class="mt-3">
        <%= @recipe.description %>
      </p>
      <% if @recipe.chef %>
        <p>Shared with you by: <%= @recipe.chef.name %></p>
      <% end %>
    </div>
  </div>
</div>